map_teams = {
    "LAL": "Los Angeles Lakers",
    "PHI": "Philadelphia 76ers",
    "SAS": "San Antonio Spurs",
    "BOS": "Boston Celtics",
    "BKN": "Brooklyn Nets",
    "SEA": "Seattle SuperSonics",
    "ATL": "Atlanta Hawks",
    "HOU": "Houston Rockets",
    "MIL": "Milwaukee Bucks",
    "PHO": "Phoenix Suns",
    "DEN": "Denver Nuggets",
    "NJN": "New Jersey Nets",
    "NYK": "New York Knicks",
    "DET": "Detroit Pistons",
    "UTA": "Utah Jazz",
    "WSB": "Washington Bullets",
    "CHI": "Chicago Bulls",
    "POR": "Portland Trail Blazers",
    "CLE": "Cleveland Cavaliers",
    "GSW": "Golden State Warriors",
    "ORL": "Orlando Magic",
    "MIA": "Miami Heat",
    "CHH": "Charlotte Hornets",
    "SAC": "Sacramento Kings",
    "MIN": "Minnesota Timberwolves",
    "TOR": "Toronto Raptors",
    "DAL": "Dallas Mavericks",
    "IND": "Indiana Pacers",
    "LAC": "Los Angeles Clippers",
    "WAS": "Washington Wizards",
    "NOH": "New Orleans Hornets",
    "TOT": "Total",
    "OKC": "Oklahoma City Thunder",
    "CHA": "Charlotte Bobcats",
    "NOP": "New Orleans Pelicans",
    "MEM": "Memphis Grizzlies",
    "KCK": "Kansas City Kings",
    "SDC": "San Diego Clippers",
}
map_teams_short = {v: k for k, v in map_teams.items()}